server:
  port: 8080
#  servlet:
#    context-path: /war-sign
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_sign?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


